# Generated by Django 3.0.4 on 2020-04-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('practice', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('K', 'Night')], default='M', max_length=1)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Instrument')),
            ],
        ),
    ]
