# Generated by Django 3.0.4 on 2020-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(verbose_name='practice time'),
        ),
    ]
