# Generated by Django 3.0.4 on 2020-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200407_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='products',
            field=models.ManyToManyField(to='main_app.Product'),
        ),
    ]
